vpc_cidr_block      = "10.0.0.0/16"
subnet_cidr_block   = "10.0.10.0/24"
avail_zone          = "us-west-1"
prefix              = "plex"
my_ip               = "49.205.249.77/32"
instance_type       = "t2.micro"
public_key_location = "C:\\Users\\msure\\OneDrive\\Desktop\\Personal\\dev-key.pub"